version: 2
cooldown:
  default-days: 7
  semver-major-days: 14
  semver-minor-days: 7
  semver-patch-days: 3
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /nodes/modules
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /templates/blank
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /packages/telemetry
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /packages/uib-fs-utils
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /packages/uib-md-utils
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /packages/uib-docsify-bundle
    schedule:
      interval: monthly

