# Would you like to sponsor my work?

# Developing open source projects takes a lot of time and effort. Any level of one-off or recuring sponsorship 
# helps focus my energies on improving the projects. If you would like to contribute, please use one of these links.

custom: ['https://paypal.me/TotallyInformation']
